name: minsk8
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_localizations:
  #   sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  permission_handler: 4.0.0 # TODO: обновить geolocator
  geolocator: 5.1.5 # TODO: обновить geolocator
  # TODO: поменять на shared_preferences? лучше hydrated_bloc!
  state_persistence: ^0.0.7
  # flutter_secure_storage

  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase_dynamic_links: ^0.7.0+1
  firebase_analytics: 5.0.16 # TODO: обновить firebase_analytics
  firebase_remote_config: ^0.6.0

  image_picker: ^0.6.7+17

  # image_cropper: 1.1.1
  # transparent_image: 1.0.0
  # pinch_zoom_image:
  #   git: git@github.com:TheFe91/pinch_zoom_image.git

  extended_image: ^1.5.0
  like_button: ^1.0.4
  # или заменить на flutter_staggered_grid_view
  loading_more_list:
    3.1.1
    # path: ../loading_more_list
  http_client_helper: ^0.2.1
  extended_nested_scroll_view:
    # 1.0.1
    # path: ../extended_nested_scroll_view/
    git: git://github.com/comerc/extended_nested_scroll_view.git
    # TODO: https://github.com/fluttercandies/extended_nested_scroll_view/pull/19
  pull_to_refresh_notification:
    # 0.3.5
    # path: ../pull_to_refresh_notification/
    git: git://github.com/comerc/pull_to_refresh_notification.git
    # TODO: https://github.com/fluttercandies/pull_to_refresh_notification/pull/14
  share: 0.6.4+3

  carousel_slider: 1.4.0 # TODO: обновить carousel_slider
  sliding_up_panel: ^1.0.2
  # auto_orientation: 1.0.6
  font_awesome_flutter: ^8.11.0

  flutter_markdown: ^0.5.1
  # webview_flutter: 0.3.22+1

  provider: ^4.3.2+3

  flutter_typeahead: ^1.9.1
  recursive_regex: 0.1.3+2

  # flutter_screenutil: 2.2.0

  flutter_local_notifications: ^3.0.2
  rxdart: ^0.24.1

  package_info: ^0.4.3+2

  intl: ^0.16.1
  # intl_translation: ^0.17.0

  url_launcher: ^5.7.10
  launch_review: ^2.0.0

  rainbow_color: ^0.1.1

  # for markdown_builder.dart
  markdown: ^3.0.0
  build: 1.3.0

  # device_preview: 0.4.7

  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.6

  bot_toast: ^3.0.5

  # animations: 1.1.2
  # flutter_neumorphic: 3.0.2
  # states_rebuilder 3.1.0
  # flare_splash_screen 3.0.1
  # catcher 0.3.20
  # map_launcher 0.12.2
  # device_simulator 0.9.6
  # image_editor_pro 1.0.6
  # flutter_lorem 1.1.0
  # freezed 0.12.1
  # rainbow_container
  # upgrader

  uuid: ^2.2.2
  crypto: ^2.1.5
  enum_to_string: ^1.0.14
  recase: ^3.0.1

  copy_with_extension: ">=1.0.0 <2.0.0"
  json_annotation: ^3.1.1
  equatable: ^1.2.5
  built_collection: ^4.3.2

  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0

  gql: ^0.12.4
  graphql: ^4.0.0-beta.6 # ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.2
  copy_with_extension_gen: ">=1.0.0 <2.0.0"
  json_serializable: ^3.5.1
  json_serializable_immutable_collections: ^0.4.2

  # pedantic: ^1.0.0
  # effective_dart: ^1.0.0
  lint: 1.3.0
  bloc_test: ^7.1.0
  mockito: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
