name: minsk8
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_localizations:
  #   sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_map: 0.10.1+1
  latlong: ^0.6.1
  permission_handler: ^4.0.0
  geolocator: ^5.1.5
  # TODO: поменять на shared_preferences?
  state_persistence: ^0.0.7
  # flutter_secure_storage

  firebase_core: ^0.5.0
  firebase_storage: ^4.0.1
  firebase_dynamic_links: 0.5.1
  firebase_analytics: 5.0.16

  image_cropper: 1.1.1
  image_picker: ^0.6.7

  # transparent_image: 1.0.0
  pinch_zoom_image:
    git: git@github.com:TheFe91/pinch_zoom_image.git

  extended_image: ^0.7.3+1
  like_button: 1.0.1
  loading_more_list:
    3.1.1
    # path: ../loading_more_list
  http_client_helper: ^0.2.1
  extended_nested_scroll_view:
    # 1.0.1
    # path: ../extended_nested_scroll_view/
    git: git://github.com/comerc/extended_nested_scroll_view.git
    # TODO: https://github.com/fluttercandies/extended_nested_scroll_view/pull/19
  pull_to_refresh_notification:
    # 0.3.5
    # path: ../pull_to_refresh_notification/
    git: git://github.com/comerc/pull_to_refresh_notification.git
    # TODO: https://github.com/fluttercandies/pull_to_refresh_notification/pull/14
  share: 0.6.4+3

  json_annotation: 3.1.0
  enum_to_string: 1.0.8
  graphql_flutter: 3.0.0

  carousel_slider: 1.4.0
  sliding_up_panel: 0.3.6 # TODO: or backdrop 0.4.6
  auto_orientation: 1.0.6
  font_awesome_flutter: 8.8.1

  flutter_markdown: 0.3.2
  # webview_flutter: 0.3.22+1

  provider: 4.1.3

  flutter_typeahead: 1.8.7
  recursive_regex: 0.1.3+2

  # flutter_screenutil: 2.2.0

  flutter_local_notifications: 1.4.4+2
  rxdart: 0.23.1

  package_info: 0.4.1

  intl: 0.16.1
  # intl_translation: ^0.17.0

  url_launcher: 5.5.0
  launch_review: 2.0.0

  rainbow_color: 0.1.1

  # for markdown_builder.dart
  markdown: 2.1.7
  build: 1.5.0

  # device_preview: 0.4.7

  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5

  bot_toast: 3.0.4
  recase: 3.0.0

  # animations: 1.1.2
  # flutter_neumorphic: 3.0.2
  # states_rebuilder 3.1.0
  # flare_splash_screen 3.0.1
  # catcher 0.3.20
  # map_launcher 0.12.2
  # device_simulator 0.9.6
  # image_editor_pro 1.0.6
  # flutter_lorem 1.1.0
  # freezed 0.12.1
  # rainbow_container
  # upgrader

  bloc: 6.0.3
  equatable: ^1.2.3
  flutter_bloc: 6.0.6
  formz: ^0.2.0
  meta: ^1.1.8
  # authentication_repository:
  #   path: packages/authentication_repository
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.3
  json_serializable: 3.5.0

  # pedantic: ^1.0.0
  # effective_dart: ^1.0.0
  lint: 1.3.0
  bloc_test: 7.0.0
  mockito: 4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
